---
title: "Research"
---
<script>
function hide_buttons(abstract) {
    var x = document.getElementById(abstract);
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}
</script>

**Banks and the Macroeconomic Transmission of Interest Rate Risk** ([Job Market Paper](content/varraso_jmp.pdf))

<button class="button_that_looks_like_link" role="button" onclick="hide_buttons('abstract_rate')">Abstract</button>
<div id="abstract_rate" style="display:none;">
I study the role of financial intermediaries in the transmission of interest rate risk. I develop a quantitative model where banks can invest in assets of different duration and choose optimally their exposure to interest rate fluctuations. I embed this portfolio problem in a heterogeneous-banks framework with financial frictions and endogenous default. The model predicts that in periods of loose monetary policy banks face weaker financial constraints. As a result, they become more tolerant of interest rate risk and invest more extensively in long-duration assets. However, when the economy undergoes a sudden monetary tightening, this portfolio shift amplifies contractions in asset prices, credit and output. I calibrate the model to match aggregate and cross-sectional patterns in banks’ duration profile. In terms of untargeted moments, I show that consistent with the data the model features (a) a negative aggregate co-movement between maturity mismatch and interest rates, and (b) a negative cross-sectional correlation between maturity mismatch and bank leverage. A quantitative application to the 2022 monetary tightening shows that a lengthening of duration in periods of low interest rates gives rise to significant financial amplification. A liquidity requirement that restricts banks' investment in long-term assets makes the economy less vulnerable to sudden interest rate raises.
</div>

### Publications

Are Collateral-Constraint Models Ready for Macroprudential Policy Design?, with [<span style="font-weight: normal">Pablo Ottonello</span>](https://sites.google.com/site/ottonellopablo/home/) and [<span style="font-weight: normal">Diego Perez</span>](https://www.perezdiego.org/), *Journal of International Economics* (2023): 139: 103650. ([Link to Submitted Paper](content/OPV_Collateral.pdf))

### Working Papers

**Impact of higher capital buffers on banks' lending and risk-taking in the short- and medium-term: evidence from the euro area experiments** with Aurea Ponte Marques and Giuseppe Cappelletti, R&R at *Journal of Financial Stability* ([Link to Paper](content/Impact_of_higher_capital_buffers.pdf))

<button class="button_that_looks_like_link" role="button" onclick="hide_buttons('abstract_buffer')">Abstract</button>
<div id="abstract_buffer" style="display:none;">
We study the impact of higher bank capital buffers, namely the other systemically important institutions (O-SII), on lending and banks' risk-taking behavior at different horizons from the first implementation. Although there is already evidence that higher capital buffers constrain credit supply and might lead to bank risk-shifting in the short-term, in this paper we shed more light on the medium-term effects of these type of policy measures. Relying on 2014 to 2017 confidential granular supervisory data, we find that O-SII banks reduced their credit supply to households and financial sectors in the short-term, shifting their lending to less risky counterparts. In the medium-term the reduction in credit supply becomes not significant from an economic perspective, whereas there is evidence that banks shift their lending to less risky borrowers within sectors. Our findings support the hypothesis that the implementation of higher capital buffers could have a positive disciplining effect by reducing banks' risk-taking. At the same time, there is evidence of only a reduced adverse impact on the real economy through a temporary decrease in credit supply restricted to the moment when there is a tightening of the macroprudential policy.
</div> 

</br>
**Optimal Fiscal Policy in Collateral-Constraint Models** ([Link to Paper](content/Fiscal_Policy_Collateral.pdf))

<button class="button_that_looks_like_link" role="button" onclick="hide_buttons('abstract_fiscal')">Abstract</button>
<div id="abstract_fiscal" style="display:none;">
I study optimal government spending in a canonical, small-open-economy model where a collateral constraint gives rise to overborrowing. I show quantitatively that excess procyclicality - a pervasive feature of emerging markets - makes the economy more vulnerable to sudden stops. In normal times, pro-cyclical spending encourages borrowing and magnifies the inefficiency; during a sudden stop, it depresses collateral values and exacerbates deleveraging pressures on households. I characterize the optimal time-consistent policy and show that it would significantly reduce both the likelihood and severity of a sudden stop.
</div> 
